apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nodejs-api
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nodejs-api
      template:
        metadata:
          labels:
            app: nodejs-api
        spec:
          containers:
          - name: nodejs-api
            image: nodejs-api:latest
            ports:
            - containerPort: 3000
